apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: directory
  name: weatherapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      name: weatherapp
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp-container
        image: 923687682943.dkr.ecr.us-west-2.amazonaws.com/weatherapp:1.5.2
        ports:
        - containerPort: 8081
